sudo: required
dist: trusty
language: node_js
node_js:
    - node
addons:
apt:
    sources:
        - google-chrome
    packages:
        - google-chrome-stable
        - google-chrome-beta
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm i -g angular-cli-ghpages
script:
    - npm run lint
    - npm run sass-lint
    - npm test
    #- ng build --prod --base-href "/Janchi-Website/"
    - ng build --prod
after_success:
    - ngh --repo=https://GH_TOKEN@github.com/dolanmiu/Janchi-Website --name="Travis CI" --email=dolan_miu@hotmail.com
